// Generated by scripts/crypto/export_site_data.py — do not edit by hand.
// Public addresses only; derived from state/crypto/wallets.json.

export interface DonationNetwork {
  network: string;
  tokens: { symbol: string; address: string }[];
}

export const DONATIONS: DonationNetwork[] = [
  {
    "network": "polygon",
    "tokens": [
      {
        "symbol": "USDC",
        "address": "0x537B27beF17eD838f31A90CAdeBa4EE748182404"
      }
    ]
  }
];
